"use client";
import { useRouter } from "next/navigation";
import { useThrottleFn } from "ahooks";
import { useCartMutation } from "@/hooks/cart";
import type { ProductVariant, ProductWithVariants } from "@/lib/db/drizzle/schema";
import { Button } from "@/components/ui/button";
import { Colors } from "./Colors";
import { useTranslations } from "@/providers/LocaleProvider";
import { ShoppingCart, Zap } from "lucide-react";
interface Props { product: ProductWithVariants; selectedVariant?: ProductVariant }
function useAction(variant?: ProductVariant) { const router = useRouter(); const { add } = useCartMutation(); const { run } = useThrottleFn(() => { if (variant) add({ variantId: variant.id }); }, { wait: 300 }); return { run, disabled: !variant || !variant.isActive || variant.stock < 1, buyNow: () => variant && router.push(`/checkout/direct?variant=${variant.id}`) }; }
export function AddToCart({ product, selectedVariant }: Props) { const a = useAction(selectedVariant); const t = useTranslations(); return <><div className="p-5"><p className="mb-3 text-sm font-semibold">{t.product.flavor}</p><Colors variants={product.variants} selectedVariantId={selectedVariant?.id} /></div><div className="grid gap-2 border-t bg-muted/20 p-4 sm:grid-cols-2"><Button type="button" variant="outline" className="h-12 gap-2 rounded-xl border-primary/40 bg-background font-bold text-primary shadow-sm hover:bg-primary/10 hover:text-primary" disabled={a.disabled} onClick={() => a.run()} aria-label={t.product.addToCart}><ShoppingCart className="size-5" aria-hidden="true" />{t.product.addToCart}</Button><Button type="button" className="h-12 gap-2 rounded-xl bg-primary font-bold shadow-lg shadow-primary/20 hover:scale-[1.01] hover:bg-primary/90" disabled={a.disabled} onClick={a.buyNow} aria-label={t.product.buyNow}><Zap className="size-5" aria-hidden="true" />{t.product.buyNow}</Button></div></>; }
export function MobileAddToCart({ product, selectedVariant }: Props) { const a = useAction(selectedVariant); const t = useTranslations(); return <div className="flex flex-col gap-2"><Colors variants={product.variants} selectedVariantId={selectedVariant?.id} compact /><div className="grid grid-cols-2 gap-2"><Button type="button" variant="outline" className="h-11 gap-1.5 rounded-xl border-primary/50 bg-background px-2 text-xs font-bold text-primary shadow-sm hover:bg-primary/10 hover:text-primary sm:text-sm" disabled={a.disabled} onClick={() => a.run()} aria-label={t.product.addToCart}><ShoppingCart className="size-4 shrink-0" aria-hidden="true" />{t.product.addToCart}</Button><Button type="button" className="h-11 gap-1.5 rounded-xl px-2 text-xs font-bold shadow-md shadow-primary/20 sm:text-sm" disabled={a.disabled} onClick={a.buyNow} aria-label={t.product.buyNow}><Zap className="size-4 shrink-0" aria-hidden="true" />{t.product.buyNow}</Button></div></div>; }
