import Link from "next/link";
import { notFound } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DirectCheckoutForm } from "@/components/checkout/DirectCheckoutForm";
import { ProductImage } from "@/components/products";
import { getUser } from "@/lib/auth/server";
import { getVariantWithProduct } from "@/services/products.service";
type Props = { searchParams: Promise<{ variant?: string }> };
export default async function DirectCheckoutPage({ searchParams }: Props) { const { variant: raw } = await searchParams; const id = Number(raw); if (!Number.isInteger(id) || id <= 0) notFound(); const [variant, user] = await Promise.all([getVariantWithProduct(id), getUser()]); if (!variant || !variant.isActive || variant.stock < 1) notFound(); return <section className="mx-auto max-w-5xl px-4 py-10"><div className="mb-8 flex items-center justify-between"><div><p className="text-xs uppercase text-muted-foreground">طلب مباشر</p><h1 className="mt-2 text-3xl font-semibold">إتمام الطلب</h1></div><Link href={`/${variant.product.category}/${variant.product.id}?variant=${variant.flavor}`}>العودة للمنتج</Link></div><div className="grid gap-6 lg:grid-cols-[1.25fr_.85fr]"><Card><CardHeader><CardTitle>بيانات التوصيل</CardTitle></CardHeader><CardContent><DirectCheckoutForm variantId={variant.id} defaultName={user?.name ?? ""} defaultEmail={user?.email ?? ""} /></CardContent></Card><Card className="h-min"><CardHeader><CardTitle>طلبك</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex gap-4"><ProductImage image={variant.images[0]} name={variant.product.name} width={80} height={112} sizes="80px" /><div><h2>{variant.product.name}</h2><p className="text-sm text-muted-foreground">{variant.flavor} · {variant.quantity}{variant.quantityUnit}</p></div></div><div className="flex justify-between border-t pt-4 font-semibold"><span>المجموع</span><span>{variant.price.toLocaleString("ar-DZ")} دج</span></div></CardContent></Card></div></section>; }
