"use client";
import { forwardRef, useImperativeHandle, useState } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { cn } from "@/lib/utils";
import type { BasicInfoData } from "@/types/admin";
export interface CategoryOption { value: string; label: string }
export type BasicInfoInitialData = Partial<BasicInfoData>;
export type BasicInfoRef = BasicInfoData & { reset: () => void };
export const BasicInfo = forwardRef<BasicInfoRef, { errors?: Record<string, string[]>; initialData?: Partial<BasicInfoData>; categories: CategoryOption[] }>(({ errors, initialData, categories }, ref) => {
  const [data, setData] = useState<BasicInfoData>({ name: initialData?.name ?? "", description: initialData?.description ?? "", brand: initialData?.brand ?? "", ingredients: initialData?.ingredients ?? "", usage: initialData?.usage ?? "", warnings: initialData?.warnings ?? "", tags: initialData?.tags ?? [], price: initialData?.price ?? 0, compareAtPrice: initialData?.compareAtPrice ?? null, category: initialData?.category ?? "", isFeatured: initialData?.isFeatured ?? false });
  useImperativeHandle(ref, () => ({ ...data, reset: () => setData({ name: "", description: "", brand: "", ingredients: "", usage: "", warnings: "", tags: [], price: 0, compareAtPrice: null, category: "", isFeatured: false }) }), [data]);
  const field = (key: keyof BasicInfoData, label: string, multiline = false) => <div className="space-y-2"><Label>{label} <span className="text-red-400">*</span></Label>{multiline ? <Textarea value={String(data[key] ?? "")} onChange={(e) => setData((d) => ({ ...d, [key]: e.target.value }))} className={cn("min-h-24", errors?.[key] && "border-red-500")} /> : <Input value={String(data[key] ?? "")} onChange={(e) => setData((d) => ({ ...d, [key]: e.target.value }))} className={cn(errors?.[key] && "border-red-500")} />}{errors?.[key] && <p className="text-sm text-red-400">{errors[key][0]}</p>}</div>;
  return <div dir="rtl" className="space-y-5">{field("name", "اسم المنتج")}{field("brand", "العلامة التجارية")}{field("description", "الوصف", true)}<div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label>السعر (دج) *</Label><Input type="number" min="0" step="0.01" value={data.price || ""} onChange={(e) => setData((d) => ({ ...d, price: Number(e.target.value) }))} /></div><div className="space-y-2"><Label>السعر قبل التخفيض</Label><Input type="number" min="0" step="0.01" value={data.compareAtPrice ?? ""} onChange={(e) => setData((d) => ({ ...d, compareAtPrice: e.target.value ? Number(e.target.value) : null }))} /></div></div><div className="space-y-2"><Label>الفئة *</Label><Select value={data.category} onValueChange={(category) => setData((d) => ({ ...d, category }))}><SelectTrigger><SelectValue placeholder="اختر الفئة" /></SelectTrigger><SelectContent>{categories.map((c) => <SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select></div>{field("ingredients", "المكونات", true)}{field("usage", "طريقة الاستخدام", true)}{field("warnings", "التحذيرات", true)}<div className="space-y-2"><Label>الوسوم</Label><Input value={data.tags.join(", ")} onChange={(e) => setData((d) => ({ ...d, tags: e.target.value.split(",").map((v) => v.trim()).filter(Boolean) }))} placeholder="بروتين، رياضة، استشفاء" /></div><label className="flex items-center justify-between rounded-lg border p-4"><span>منتج مميز</span><input type="checkbox" checked={data.isFeatured} onChange={(e) => setData((d) => ({ ...d, isFeatured: e.target.checked }))} /></label></div>;
});
BasicInfo.displayName = "BasicInfo";
