"use client";
import { forwardRef, useImperativeHandle, useRef, useState } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { VariantImages, type VariantImagesRef } from "./VariantImages";
import type { VariantFormData, VariantSubmitData } from "@/types/admin";
import { SupplementFormZod, QuantityUnitZod } from "@/lib/db/drizzle/schema";
export type VariantFormRef = { getData: () => VariantSubmitData; getImages: () => File[]; reset: () => void };
export const VariantForm = forwardRef<VariantFormRef, { index: number; onRemove: () => void; canRemove?: boolean; initialData?: VariantFormData }>(({ index, onRemove, canRemove = true, initialData }, ref) => {
  const imagesRef = useRef<VariantImagesRef>(null!);
  const [data, setData] = useState<VariantFormData>(initialData ?? { flavor: "", form: "other", quantity: 1, quantityUnit: "piece", servings: null, sku: "", price: 0, compareAtPrice: null, stock: 0, images: [], isActive: true });
  useImperativeHandle(ref, () => ({ getData: () => { const i = imagesRef.current; return { ...data, imageCount: i?.images.length ?? 0, existingImages: i?.existingImages ?? [], removedImages: i?.removedExistingImages ?? [] }; }, getImages: () => imagesRef.current?.images ?? [], reset: () => { setData(initialData ?? { flavor: "", form: "other", quantity: 1, quantityUnit: "piece", servings: null, sku: "", price: 0, compareAtPrice: null, stock: 0, images: [], isActive: true }); imagesRef.current?.reset(); } }), [data, initialData]);
  const set = (key: keyof VariantFormData, value: unknown) => setData((d) => ({ ...d, [key]: value }));
  return <Card dir="rtl"><CardHeader className="flex flex-row items-center justify-between"><span className="font-semibold">متغير المنتج {index + 1}</span>{canRemove && <Button type="button" variant="ghost" onClick={onRemove}>حذف</Button>}</CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div><Label>النكهة *</Label><Input value={data.flavor} onChange={(e) => set("flavor", e.target.value)} placeholder="شوكولاتة" /></div><div><Label>الشكل *</Label><Select value={data.form} onValueChange={(v) => set("form", v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{SupplementFormZod.options.map((v) => <SelectItem key={v} value={v}>{({ powder: "مسحوق", capsules: "كبسولات", tablets: "أقراص", liquid: "سائل", gummies: "علكة", bars: "بار", other: "أخرى" } as Record<string, string>)[v]}</SelectItem>)}</SelectContent></Select></div><div><Label>الكمية *</Label><Input type="number" min="0.01" value={data.quantity} onChange={(e) => set("quantity", Number(e.target.value))} /></div><div><Label>الوحدة *</Label><Select value={data.quantityUnit} onValueChange={(v) => set("quantityUnit", v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{QuantityUnitZod.options.map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div><div><Label>عدد الحصص</Label><Input type="number" min="1" value={data.servings ?? ""} onChange={(e) => set("servings", e.target.value ? Number(e.target.value) : null)} /></div><div><Label>SKU *</Label><Input value={data.sku} onChange={(e) => set("sku", e.target.value)} placeholder="WHEY-CHOC-1KG" /></div><div><Label>السعر (دج) *</Label><Input type="number" min="0" value={data.price || ""} onChange={(e) => set("price", Number(e.target.value))} /></div><div><Label>السعر قبل التخفيض</Label><Input type="number" min="0" value={data.compareAtPrice ?? ""} onChange={(e) => set("compareAtPrice", e.target.value ? Number(e.target.value) : null)} /></div><div><Label>المخزون *</Label><Input type="number" min="0" value={data.stock} onChange={(e) => set("stock", Number(e.target.value))} /></div><div className="flex items-center gap-2 pt-6"><input type="checkbox" checked={data.isActive} onChange={(e) => set("isActive", e.target.checked)} /><Label>متاح للبيع</Label></div><div className="sm:col-span-2"><Label>صور المتغير *</Label><VariantImages ref={imagesRef} initialImages={initialData?.images} /></div></CardContent></Card>;
});
VariantForm.displayName = "VariantForm";
